
{
  field: 'dept_name',
  title: 'Departemen',
  sortable:true,
  order:true,
  searchable:true,
  align: 'left',
  valign: 'middle',
},
{
  field: 'vendor_name',
  title: 'Vendor',
  sortable:true,
  order:true,
  searchable:true,
  align: 'left',
  valign: 'middle',
},
{
  field: 'contract_number',
  title: 'Nomor Kontrak',
  sortable:true,
  order:true,
  searchable:true,
  align: 'center',
  valign: 'middle',
},
{
  field: 'contract_qty',
  title: 'Qty Kontrak',
  sortable:true,
  order:true,
  searchable:true,
  align: 'center',
  valign: 'middle',
},
{
  field: 'wo_number',
  title: 'Nomor PO',
  sortable:true,
  order:true,
  searchable:true,
  align: 'center',
  valign: 'middle',
},
{
  field: 'wo_price',
  title: 'Harga PO',
  sortable:true,
  order:true,
  searchable:true,
  align: 'right',
  valign: 'middle',
  formatter: number_format,
},
{
  field: 'wo_qty',
  title: 'PO Qty',
  sortable:true,
  order:true,
  searchable:true,
  align: 'center',
  valign: 'middle',
  width:'14%',
},

{
  field: 'si_number',
  title: 'No SI',
  sortable:true,
  order:true,
  searchable:true,
  align: 'center',
  valign: 'middle',
  width:'14%',
},
{
  field: 'sppm_number',
  title: 'No. SPPM',
  sortable:true,
  order:true,
  searchable:true,
  align: 'left',
  valign: 'middle',
  width:'14%',
},
{
  field: 'do_number',
  title: 'Nomor DO',
  sortable:true,
  order:true,
  searchable:true,
  align: 'left',
  valign: 'middle',
  width:'14%',
},
{
  field: 'do_qty',
  title: 'DO Qty',
  sortable:true,
  order:true,
  searchable:true,
  align: 'left',
  valign: 'middle',
  width:'14%',
},
{
  field: 'sj_number',
  title: 'Nomor SJ',
  sortable:true,
  order:true,
  searchable:true,
  align: 'left',
  valign: 'middle',
  width:'14%',
},
{
  field: 'sj_qty',
  title: 'SJ Qty',
  sortable:true,
  order:true,
  searchable:true,
  align: 'left',
  valign: 'middle',
  width:'14%',
},
{
  field: 'bapb_number',
  title: 'Nomor BAST',
  sortable:true,
  order:true,
  searchable:true,
  align: 'left',
  valign: 'middle',
  width:'14%',
},
{
  field: 'bapb_qty',
  title: 'BAST Qty',
  sortable:true,
  order:true,
  searchable:true,
  align: 'left',
  valign: 'middle',
  width:'14%',
},
{
  field: 'inv_number',
  title: 'Nomor Invoice',
  sortable:true,
  order:true,
  searchable:true,
  align: 'left',
  valign: 'middle',
  width:'14%',
},
{
  field: 'inv_qty',
  title: 'Inv Qty',
  sortable:true,
  order:true,
  searchable:true,
  align: 'left',
  valign: 'middle',
  width:'14%',
},
{
  field: 'inv_price',
  title: 'Harga Inv',
  sortable:true,
  order:true,
  searchable:true,
  align: 'right',
  valign: 'middle',
  formatter: number_format,
},
